name: Deploy Website to S3

on:
  push:
    branches:
      - deploying

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://globaljobkorea --delete

      # - name: CloudFront Invalidation
      #   uses: chetan/invalidate-cloudfront-action@master
      #   with:
      #     distribution-id: ${{ secrets.DISTRIBUTION_ID }}
      #     paths: '/*'
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
